
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = ""

###############################################################
# Verbs and shortcuts

# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
#   export EDITOR=/usr/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
#
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

# If you uncomment the two next shortcuts, the left
# and right arrow keys will be used to go to the parent
# directory or to open a selected one:
#
# [[verbs]]
# key = "left"
# execution = ":parent"
#
# [[verbs]]
# key = "right"
# execution = ":focus"

# Another popular set of shorctuts for going up and down:
#
 [[verbs]]
 key = "ctrl-j"
 execution = ":line_down"

 [[verbs]]
 key = "ctrl-k"
 execution = ":line_up"

 [[verbs]]
 key = "ctrl-d"
 execution = ":page_down"

 [[verbs]]
 key = "ctrl-u"
 execution = ":page_up"

# If you develop using git, you might like to often switch
# to the "git status" filter:

 [[verbs]]
 key = "ctrl-g"
 execution = ":toggle_git_status"

###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
# Note that some of those colors might not correcly
# render on terminals with low capabilities.
#

[skin]
default = "rgb(60, 56, 54) rgb(251, 241, 199)"
tree = "rgb(146, 131, 116) None"
file = "ansi(237) None"
directory = "ansi(237) None Bold"
exe = "ansi(106) None"
link = "ansi(66) None"
pruning = "ansi(136) None Italic"
perm__ = "gray(5) None"
perm_r = "ansi(94) None"
perm_w = "ansi(132) None"
perm_x = "ansi(65) None"
owner = "ansi(138) None"
group = "ansi(131) None"
dates = "ansi(66) None"
sparse = "ansi(214) None"
git_branch = "ansi(229) None"
git_insertions = "ansi(28) None"
git_deletions = "ansi(160) None"
git_status_current = "gray(5) None"
git_status_modified = "ansi(28) None"
git_status_new = "ansi(94) None Bold"
git_status_ignored = "gray(17) None"
git_status_conflicted = "ansi(88) None"
git_status_other = "ansi(88) None"
selected_line = "None rgb(214, 193, 161) / None gray(21)"
char_match = "ansi(22) None"
file_error = "Red None"
flag_label = "gray(9) None"
flag_value = "ansi(166) None Bold"
input = "rgb(60, 56, 54) None / gray(4) gray(20)"
status_error = "gray(22) ansi(124)"
status_normal = "rgb(60, 56, 54) rgb(189, 174, 147)"
status_job = "ansi(220) gray(5)"
status_italic = "ansi(166) rgb(189, 174, 147)"
status_bold = "ansi(166) rgb(189, 174, 147) Bold"
status_code = "ansi(17) rgb(189, 174, 147)"
status_ellipsis = "gray(19) gray(15)"
purpose_normal = "gray(20) gray(2)"
purpose_italic = "ansi(178) gray(2)"
purpose_bold = "ansi(178) gray(2) Bold"
purpose_ellipsis = "gray(20) gray(2)"
scrollbar_track = "gray(20) none"
scrollbar_thumb = "ansi(238) none"
help_paragraph = "gray(2) none"
help_bold = "ansi(202) none bold"
help_italic = "ansi(202) none italic"
help_code = "gray(5) gray(22)"
help_headers = "ansi(202) none"
help_table_border = "ansi(239) None"

# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds

